#############################################################
# Order Service API Testing
#############################################################

@host=http://localhost:8080

#############################################################
# Create Order
#############################################################

POST {{host}}/orders
Content-Type: application/json

{
  "customerName": "Manivannan",
  "amount": 2500
}

###

#############################################################
# Create Another Order
#############################################################

POST {{host}}/orders
Content-Type: application/json

{
  "customerName": "John",
  "amount": 4500
}

###

#############################################################
# Create Another Order
#############################################################

POST {{host}}/orders
Content-Type: application/json

{
  "customerName": "David",
  "amount": 9000
}

###

#############################################################
# Get All Orders
#############################################################

GET {{host}}/orders

###

#############################################################
# Get Order By UUID
#############################################################

GET {{host}}/orders/019f60b1-c93c-791c-91c0-888c877d0422

###

#############################################################
# Update Order
#############################################################

PUT {{host}}/orders/0198074d-fd0d-7d4c-a59c-3f84d49d0d0d
Content-Type: application/json

{
  "customerName": "Manivannan Updated",
  "amount": 8000
}

###

#############################################################
# Delete Order
#############################################################

DELETE {{host}}/orders/0198074d-fd0d-7d4c-a59c-3f84d49d0d0d

###

#############################################################
# Health Check
#############################################################

GET {{host}}/actuator/health

###